import Footer from '../components/Footer';
import Header from '../components/Header';
import Head from 'next/head';
import styles from '../styles/Layout.module.css';
import Container from 'react-bootstrap/Container';

const Layout: React.FC<{}> = ({ children }) => (
  <div className={`bg-light mx-auto  ${styles.layout}`}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
    <Container fluid>
      <main className="min-vh-100 px-3">{children}</main>
    </Container>
    <Footer />
  </div>
);

export default Layout;
